# -*- coding: utf-8 -*-
"""ProvaAv2_SAD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqaUf3jXi8B4PNxcBCtLtSy5NiKX8i38

DISCIPLINA: Sistemas de Apoio à Decisão 	PROFESSOR(A): Alex Salgado 
 
PERÍODO: 7o. 				TURNO: noite 		AVALIAÇÃO: 
 
ALUNO(A): _________________________________________________________
 
GRAU: 							VISTO DO PROFESSOR:
 
Preencha sua resposta no próprio arquivo do Jupyter e depois me envie no link abaixo:
resposta: https://goo.gl/forms/wuTdyyNoVXwVfD7v2

## Questão 1 - valor (0,00)
1.1 - Importar os modulos python para machine learn e carregar o arquivo pacotes.xlsx usando o método read_excel do pandas
"""

import pandas as pd
dt = pd.read_excel("pacotes.xlsx")

"""1.2 - Exibir os primeiros registros desta tabela"""



"""## Questão 2 - valor (0,5)
Utilizando as terminologias de Machine Learning(features e observações):  
2.1 - Quantas "features" têm nessa base de dados?
"""



"""2.2 - Quantas observações têm nessa base de dados?"""



"""## Questão 3 - valor (2,0)
3.1 - Usando o algoritmo de LogisticRegression, qual a previsão? Adivinhe qual é o pacote com peso 770g, largura 26.8 cm, altura 15.62 cm, ou seja, com as seguintes features (peso = 779, largura=26.8, altura=15.62).
"""



"""## Questão 4 - valor (2,5)
Usando o método de avaliação de acurácia (Treinar e testar na base de dados inteira/Train test entire model), Calcular a acurácia de cada um dos 3 métodos abaixo.  



4.1 - Acurácia usando o algoritmo de KNN (com 1 vizinho, k=1)
"""



"""4.2 - Acurácia usando o algoritmo de KNN (com 5 vizinho, k=5)"""



"""4.3 - Acurácia usando o algoritmo de LogisticRegression"""



"""4.4 - De acordo com seus resultados anteriores, qual dos 3 métodos é mais eficiente?"""